#!/usr/bin/env python3
"""Export this repository's Claude Code sessions as redacted Markdown transcripts.

Usage: /usr/bin/python3 scripts/export_transcripts.py [--source DIR] [--out DIR]

Reads Claude Code's local session files (~/.claude/projects/<repo-path-slug>/*.jsonl)
and writes one Markdown transcript per session to ai_transcripts/. Unchanged
transcripts aren't rewritten. See the Transcripts rule in ai_log.md.

Standard library only, and compatible with the Python 3.9 that ships with Xcode.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date, datetime, tzinfo
from pathlib import Path
from typing import List, Optional

MAX_RESULT_LINES = 40

EMAIL = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,}")
REMINDER = re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL)
COMMAND = re.compile(r"<command-name>(.*?)</command-name>.*?<command-args>(.*?)</command-args>", re.DOTALL)
HARNESS_PREFIXES = ("<local-command-caveat>", "<local-command-stdout>", "<task-notification>")

NOTE = (
    "> Generated by `scripts/export_transcripts.py` from Claude Code's local session file. "
    "Don't edit by hand; re-run the export instead. Email addresses and the home directory path "
    "are redacted. System context, harness metadata, and images are left out, and each tool result "
    f"is cut to its first {MAX_RESULT_LINES} lines. Claude Code doesn't store the AI's reasoning "
    "(it's saved as empty blocks) or the progress updates it writes between tool calls, so neither "
    "appears here."
)


# Parsing


def load(path: Path) -> List[dict]:
    """Returns the session file's entries, skipping lines that aren't valid JSON."""
    entries = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            entries.append(json.loads(line))
        except ValueError:
            continue
    return entries


def is_queued_human(entry: dict) -> bool:
    attachment = entry.get("attachment") or {}
    origin = attachment.get("origin") or {}
    return (
        entry.get("type") == "attachment"
        and attachment.get("type") == "queued_command"
        and origin.get("kind") == "human"
    )


def is_conversation(entry: dict) -> bool:
    return bool(entry.get("timestamp")) and (entry.get("type") in ("user", "assistant") or is_queued_human(entry))


def parse_time(stamp: str, tz: Optional[tzinfo]) -> datetime:
    return datetime.fromisoformat(stamp.replace("Z", "+00:00")).astimezone(tz)


def session_id(entries: List[dict]) -> str:
    return next((e["sessionId"] for e in entries if e.get("sessionId")), "unknown")


# Formatting


def fence(body: str, language: str = "") -> str:
    longest = max((len(run) for run in re.findall(r"`+", body)), default=0)
    ticks = "`" * max(3, longest + 1)
    return f"{ticks}{language}\n{body}\n{ticks}"


def inline_code(value: str) -> str:
    longest = max((len(run) for run in re.findall(r"`+", value)), default=0)
    ticks = "`" * (longest + 1)
    pad = " " if value.startswith("`") or value.endswith("`") else ""
    return f"{ticks}{pad}{value}{pad}{ticks}"


def quote(body: str) -> str:
    return "\n".join(f"> {line}" if line else ">" for line in body.split("\n"))


class Renderer:
    def __init__(self, tz: Optional[tzinfo], home: str) -> None:
        self.tz = tz
        self.home = re.compile(re.escape(home) + r"(?![A-Za-z0-9_.-])")
        self.start_day: Optional[date] = None

    def redact(self, body: str) -> str:
        body = EMAIL.sub("[email redacted]", body)
        return self.home.sub("~", body)

    def clean(self, body: str) -> str:
        # The harness injects reminders only into prompts and tool results, never into what the AI writes.
        return self.redact(REMINDER.sub("", body))

    def time(self, stamp: str) -> str:
        moment = parse_time(stamp, self.tz)
        if moment.date() == self.start_day:
            return moment.strftime("%H:%M:%S")
        return moment.strftime("%Y-%m-%d %H:%M:%S")

    def blocks_text(self, content) -> str:
        if isinstance(content, str):
            return content
        parts = []
        for block in content or []:
            kind = block.get("type")
            if kind == "text":
                parts.append(block.get("text", ""))
            else:
                parts.append(f"[{kind} omitted]")
        return "\n".join(parts)

    def human(self, stamp: str, body: str, label: str = "Human") -> Optional[str]:
        body = self.clean(body).strip()
        if not body:
            return None
        return f"### {self.time(stamp)} · {label}\n\n{quote(body)}"

    def user(self, entry: dict) -> List[str]:
        if entry.get("isMeta"):
            return []
        stamp = entry["timestamp"]
        content = entry["message"].get("content")
        if isinstance(content, str):
            stripped = REMINDER.sub("", content).strip()
            if stripped.startswith(HARNESS_PREFIXES):
                return []
            command = COMMAND.search(stripped)
            if command:
                name, args = command.group(1).strip(), command.group(2).strip()
                stripped = inline_code(f"{name} {args}".strip())
            rendered = self.human(stamp, stripped)
            return [rendered] if rendered else []

        out = []
        prompt = [b for b in content if b.get("type") != "tool_result"]
        for block in content:
            if block.get("type") == "tool_result":
                out.append(self.result(stamp, block))
        if prompt:
            rendered = self.human(stamp, self.blocks_text(prompt))
            if rendered:
                out.append(rendered)
        return out

    def assistant(self, entry: dict) -> List[str]:
        stamp = entry["timestamp"]
        out = []
        for block in entry["message"].get("content") or []:
            kind = block.get("type")
            if kind == "text":
                body = self.redact(block.get("text", "")).strip()
                if body:
                    out.append(f"### {self.time(stamp)} · Claude\n\n{body}")
            elif kind == "tool_use":
                out.append(self.call(stamp, block))
        return out

    def call(self, stamp: str, block: dict) -> str:
        name = block.get("name", "tool")
        tool_input = dict(block.get("input") or {})
        title = f"**{self.time(stamp)} · Tool call: {name}**"
        description = tool_input.get("description")
        if isinstance(description, str) and "\n" not in description:
            title += f" — {self.redact(description)}"
            del tool_input["description"]
        parts = [title]
        if name == "Bash" and isinstance(tool_input.get("command"), str):
            parts.append(fence(self.redact(tool_input.pop("command")), "sh"))
        items = []
        for key, value in tool_input.items():
            if isinstance(value, str) and "\n" in value:
                items.append(f"- `{key}`:\n\n{fence(self.redact(value))}")
            else:
                shown = value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)
                items.append(f"- `{key}`: {inline_code(self.redact(shown))}")
        if items:
            parts.append("\n".join(items))
        return "\n\n".join(parts)

    def result(self, stamp: str, block: dict) -> str:
        label = "Tool error" if block.get("is_error") else "Tool result"
        body = self.clean(self.blocks_text(block.get("content"))).strip("\n")
        title = f"**{self.time(stamp)} · {label}**"
        if not body.strip():
            return f"{title}\n\n_(empty)_"
        lines = body.split("\n")
        rendered = f"{title}\n\n{fence(chr(10).join(lines[:MAX_RESULT_LINES]))}"
        if len(lines) > MAX_RESULT_LINES:
            rendered += f"\n\n_{len(lines) - MAX_RESULT_LINES} more lines omitted._"
        return rendered


# Public API


def render_session(entries: List[dict], tz: Optional[tzinfo] = None, home: Optional[str] = None) -> str:
    """Renders one session's entries as a Markdown transcript."""
    renderer = Renderer(tz, home or str(Path.home()))
    conversation = [e for e in entries if is_conversation(e)]
    start = parse_time(conversation[0]["timestamp"], tz)
    end = parse_time(conversation[-1]["timestamp"], tz)
    renderer.start_day = start.date()

    sid = session_id(entries)
    models = list(dict.fromkeys(e["message"].get("model") for e in entries if e.get("type") == "assistant"))
    versions = list(dict.fromkeys(e["version"] for e in conversation if e.get("version")))
    header = [
        f"# Claude Code session `{sid[:8]}`",
        "\n".join(
            [
                f"- **Started:** {start.strftime('%Y-%m-%d %H:%M:%S %z')}",
                f"- **Ended:** {end.strftime('%Y-%m-%d %H:%M:%S %z')}",
                f"- **Session ID:** `{sid}`",
                f"- **Model:** {', '.join(m for m in models if m) or 'unknown'}",
                f"- **Claude Code version:** {', '.join(versions) or 'unknown'}",
            ]
        ),
        NOTE,
        "## Transcript",
    ]

    body = []
    for entry in conversation:
        if entry["type"] == "user":
            body.extend(renderer.user(entry))
        elif entry["type"] == "assistant":
            body.extend(renderer.assistant(entry))
        else:
            rendered = renderer.human(
                entry["timestamp"], renderer.blocks_text(entry["attachment"].get("prompt")), "Human (sent mid-turn)"
            )
            if rendered:
                body.append(rendered)
    return "\n\n".join(header + body) + "\n"


def output_name(entries: List[dict], tz: Optional[tzinfo] = None) -> str:
    """Returns the transcript's file name: local start time plus the session ID prefix."""
    first = next(e for e in entries if is_conversation(e))
    start = parse_time(first["timestamp"], tz)
    return f"{start.strftime('%Y-%m-%d-%H%M')}-{session_id(entries)[:8]}.md"


def default_source_dir(repo, home: Optional[str] = None) -> Path:
    """Returns the directory where Claude Code keeps session files for the repo."""
    slug = re.sub(r"[^A-Za-z0-9]", "-", str(repo))
    return Path(home or str(Path.home())) / ".claude" / "projects" / slug


def export(source: Path, out: Path, tz: Optional[tzinfo] = None, home: Optional[str] = None) -> List[Path]:
    """Writes a transcript for every session in `source` and returns the files that changed."""
    out.mkdir(parents=True, exist_ok=True)
    written = []
    for path in sorted(source.glob("*.jsonl")):
        entries = load(path)
        if not any(is_conversation(e) for e in entries):
            continue
        target = out / output_name(entries, tz)
        rendered = render_session(entries, tz, home)
        if target.exists() and target.read_text(encoding="utf-8") == rendered:
            continue
        target.write_text(rendered, encoding="utf-8")
        written.append(target)
    return written


def main(argv: Optional[List[str]] = None) -> int:
    repo = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Export Claude Code sessions as Markdown transcripts.")
    parser.add_argument("--source", type=Path, default=default_source_dir(repo))
    parser.add_argument("--out", type=Path, default=repo / "ai_transcripts")
    args = parser.parse_args(argv)
    if not args.source.is_dir():
        print(f"No Claude Code session directory at {args.source}", file=sys.stderr)
        return 1
    written = export(args.source, args.out)
    for path in written:
        print(f"Updated {path.name}")
    print(f"{len(written)} transcript(s) updated in {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
